"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { apiFetch, createStory, type Product } from "@/lib/api";
type Draft={product_id:string;title:string;content:string;color_tag:string;color_hex:string;visibility:"public"|"followers"};
const empty:Draft={product_id:"",title:"",content:"",color_tag:"",color_hex:"#c9a84c",visibility:"public"};
export default function WriteStoryPage(){const router=useRouter();const editor=useRef<HTMLDivElement>(null);const [draft,setDraft]=useState<Draft>(empty);const [products,setProducts]=useState<Product[]>([]);const [images,setImages]=useState<string[]>([]);const [error,setError]=useState("");
 useEffect(()=>{if(!sessionStorage.getItem("keycloak_access_token")){location.href=`${process.env.NEXT_PUBLIC_KEYCLOAK_URL || "/auth/login"}?redirect_uri=${encodeURIComponent(location.href)}`;return;}const stored=sessionStorage.getItem("story_draft");if(stored)setDraft(JSON.parse(stored) as Draft);void apiFetch<Product[]>("/passport/my-products").then(setProducts).catch(()=>setError("Could not load your jewelry."));},[]);
 useEffect(()=>{sessionStorage.setItem("story_draft",JSON.stringify(draft));},[draft]);
 function selectProduct(id:string){const product=products.find(p=>p.id===id);setDraft(value=>({...value,product_id:id,color_tag:product?.gem_color||value.color_tag,color_hex:product?.gem_color_hex||value.color_hex}));}
 function filesChanged(files:FileList|null){if(!files)return;const selected=Array.from(files).slice(0,5);setImages(selected.map(URL.createObjectURL));}
 async function submit(event:FormEvent){event.preventDefault();try{await createStory({...draft,media_urls:[]});sessionStorage.removeItem("story_draft");router.push("/community");}catch(e){setError(e instanceof Error?e.message:"Publishing failed");}}
 return <main className="mx-auto min-h-screen max-w-2xl px-5 py-12"><h1 className="font-display mb-8 text-5xl">Write your story</h1><form onSubmit={submit} className="luxury-card space-y-5">{error&&<p className="text-red-300">{error}</p>}<label className="block">Your jewelry<select required value={draft.product_id} onChange={e=>selectProduct(e.target.value)} className="mt-2 w-full rounded-lg bg-black p-3"><option value="">Select a piece</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="grid grid-cols-[1fr_auto] gap-4"><label>Color tag<input value={draft.color_tag} onChange={e=>setDraft({...draft,color_tag:e.target.value})} className="mt-2 w-full rounded-lg bg-black p-3"/></label><label>Color<input type="color" value={draft.color_hex} onChange={e=>setDraft({...draft,color_hex:e.target.value})} className="mt-2 block h-12 w-16 bg-transparent"/></label></div><label className="block">Title<input required maxLength={255} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="mt-2 w-full rounded-lg bg-black p-3"/></label><label className="block">Story<div ref={editor} contentEditable suppressContentEditableWarning role="textbox" onInput={e=>setDraft({...draft,content:e.currentTarget.textContent||""})} className="mt-2 min-h-40 rounded-lg bg-black p-3">{draft.content}</div><span className="text-xs text-zinc-500">{draft.content.length} characters · Use plain text and line breaks</span></label><label className="block">Photos (up to 5)<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>filesChanged(e.target.files)} className="mt-2 block"/></label><div className="flex gap-2">{images.map((src,i)=><div key={src} className="size-20 rounded bg-cover bg-center" style={{backgroundImage:`url(${src})`}} aria-label={`Preview ${i+1}`}/>)}</div><fieldset><legend>Visibility</legend><div className="mt-2 flex gap-5">{(["public","followers"] as const).map(v=><label key={v}><input type="radio" checked={draft.visibility===v} onChange={()=>setDraft({...draft,visibility:v})}/> {v==="public"?"Public":"Only Followers"}</label>)}</div></fieldset><button disabled={!draft.content||!draft.product_id} className="gold-button disabled:opacity-40">Publish story</button></form></main>}
