"use client";
import { useEffect, useState } from "react";
import { apiFetch, type Product, type Story } from "@/lib/api";
type Tab="Products"|"QR Management"|"Moderation Queue"|"Analytics";
function roleFromToken(token:string):string[]{try{return (JSON.parse(atob(token.split(".")[1])) as {realm_access?:{roles?:string[]}}).realm_access?.roles||[];}catch{return[];}}
export default function AdminPage(){const [tab,setTab]=useState<Tab>("Products");const [products,setProducts]=useState<Product[]>([]);const [stories,setStories]=useState<Story[]>([]);const [search,setSearch]=useState("");const [showForm,setShowForm]=useState(false);const [form,setForm]=useState({sku:"",name:"",gem_type:"",gem_color:"",gem_color_hex:"#c9a84c"});const [qr,setQr]=useState("");
 useEffect(()=>{const token=sessionStorage.getItem("keycloak_access_token");if(!token||!roleFromToken(token).includes("admin")){location.href="/";return;}void apiFetch<Product[]>("/passport/products").then(setProducts);void apiFetch<{items:Story[]}>("/social/moderation").then(r=>setStories(r.items));},[]);
 async function add(){const product=await apiFetch<Product>("/passport/products",{method:"POST",body:JSON.stringify(form)});setProducts(v=>[product,...v]);setShowForm(false);}
 async function generate(id:string){const result=await apiFetch<{qr_image_url:string}>(`/admin/qr/generate/${id}`,{method:"POST"});setQr(result.qr_image_url);}
 async function moderate(id:string,approve:boolean){const reason=approve?undefined:prompt("Rejection reason");if(!approve&&!reason)return;await apiFetch(`/social/moderation/${id}/${approve?"approve":"reject"}`,{method:"POST",body:JSON.stringify({reason})});setStories(v=>v.filter(s=>s.id!==id));}
 const filtered=products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="min-h-screen px-5 py-10 md:px-10"><h1 className="font-display text-5xl text-[#c9a84c]">Administration</h1><nav className="my-8 flex gap-2 overflow-x-auto">{(["Products","QR Management","Moderation Queue","Analytics"] as Tab[]).map(t=><button onClick={()=>setTab(t)} key={t} className={`shrink-0 rounded-full px-4 py-2 ${tab===t?"bg-[#c9a84c] text-black":"bg-zinc-800"}`}>{t}</button>)}</nav>
 {tab==="Products"&&<section className="luxury-card"><div className="mb-5 flex justify-between gap-3"><input placeholder="Search products" value={search} onChange={e=>setSearch(e.target.value)} className="rounded-lg bg-black p-3"/><button className="gold-button" onClick={()=>setShowForm(true)}>Add Product</button></div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Name</th><th>SKU</th><th>Gem</th><th>Action</th></tr></thead><tbody>{filtered.map(p=><tr className="border-t border-zinc-800" key={p.id}><td className="py-4">{p.name}</td><td>{p.sku}</td><td>{p.gem_type}</td><td><button className="text-[#c9a84c]" onClick={()=>generate(p.id)}>Generate QR</button></td></tr>)}</tbody></table></div></section>}
 {tab==="QR Management"&&<section className="luxury-card"><h2 className="font-display text-2xl">Scan log & fraud alerts</h2><p className="mt-4 text-zinc-400">Live scan activity and revocation controls are shown here when events arrive.</p><span className="mt-4 inline-block rounded-full bg-emerald-950 px-3 py-1 text-emerald-300">No active fraud alerts</span></section>}
 {tab==="Moderation Queue"&&<section className="space-y-3">{stories.map(s=><article className="luxury-card" key={s.id}><b>{s.title}</b><p className="my-3 line-clamp-3 text-zinc-400">{s.content}</p><button onClick={()=>moderate(s.id,true)} className="mr-3 text-emerald-400">Approve</button><button onClick={()=>moderate(s.id,false)} className="text-red-400">Reject</button></article>)}</section>}
 {tab==="Analytics"&&<section className="grid gap-4 sm:grid-cols-3">{[["Products",products.length],["Pending stories",stories.length],["Fraud alerts",0]].map(([k,v])=><div className="luxury-card" key={k}><p className="text-zinc-500">{k}</p><strong className="font-display text-4xl text-[#c9a84c]">{v}</strong></div>)}</section>}
 {showForm&&<div className="fixed inset-0 grid place-items-center bg-black/80 p-5"><div className="luxury-card w-full max-w-xl"><h2 className="font-display mb-5 text-3xl">Product details</h2>{Object.keys(form).map(key=><label className="mb-3 block capitalize" key={key}>{key.replaceAll("_"," ")}<input type={key==="gem_color_hex"?"color":"text"} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 block w-full rounded bg-black p-3"/></label>)}<label>Certificates<input type="file" multiple accept="application/pdf,image/png,image/jpeg" className="block py-3"/></label><details className="my-3"><summary>Design story</summary><textarea className="mt-2 w-full rounded bg-black p-3" placeholder="Inspiration and craft process"/></details><button onClick={add} className="gold-button">Save</button><button onClick={()=>setShowForm(false)} className="ml-4">Cancel</button></div></div>}
 {qr&&<div className="fixed inset-0 grid place-items-center bg-black/80"><div className="luxury-card text-center"><div className="mx-auto size-64 bg-contain bg-center bg-no-repeat" style={{backgroundImage:`url(${qr})`}}/><a href={qr} download className="gold-button mt-4">Download QR</a><button className="ml-4" onClick={()=>setQr("")}>Close</button></div></div>}</main>}
